version: "3.8"

services:
  # ZOOKEEPER (Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    profiles: ["kafka"]
    networks:
      - bigdata-net

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    profiles: ["kafka"]
    networks:
      - bigdata-net

  # HADOOP NAMENODE
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=test-cluster
    volumes:
      - namenode:/hadoop/dfs/name
    profiles: ["hive"]
    networks:
      - bigdata-net

  # HADOOP DATANODE
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    profiles: ["hive"]
    networks:
      - bigdata-net

  # POSTGRESQL para Hive Metastore
  hivemetastoredb:
    image: postgres:13
    container_name: hivemetastoredb
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    profiles: ["hive"]
    volumes:
      - metastore-db:/var/lib/postgresql/data
    networks:
      - bigdata-net

  # HIVE METASTORE
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    depends_on:
      - namenode
      - datanode
      - hivemetastoredb
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hivemetastoredb:5432/metastore
      HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
      HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword: hive
      HIVE_METASTORE_PORT: 9083
    ports:
      - "9083:9083"
    profiles: ["hive"]
    networks:
      - bigdata-net

  # IMPALA
  impala:
    image: apache/impala:4.5.0-impala_quickstart_hms
    container_name: impala
    ports:
      - "25000:25000"  # Web UI
      - "21050:21050"  # JDBC/ODBC
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    command: bash -c "while true; do sleep 1000; done"
    depends_on:
      - hive-metastore
      - namenode
      - datanode
    profiles: ["impala"]
    networks:
      - bigdata-net

  # SPARK MASTER
  spark:
    image: bitnami/spark:3.3
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    profiles: ["spark"]
    networks:
      - bigdata-net

  # SPARK APP PYTHON
  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    volumes:
      - ./src:/app
      - ./data:/app/data
    depends_on:
      - spark
    command: sleep infinity
    profiles: ["spark"]
    networks:
      - bigdata-net

  spark-app-run:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app-run
    volumes:
      - ./src:/app
      - ./data:/app/data
    depends_on:
      - spark
    command: sleep infinity
    profiles: ["spark"]
    networks:
      - bigdata-net
    ports:
    - "8000:8000"

volumes:
  namenode:
  datanode:
  metastore-db:

networks:
  bigdata-net:
