services:
  # ZOOKEEPER (kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    profiles: ["kafka"]

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    profiles: ["kafka"]

  # HADOOP NAMENODE (hive)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=test-cluster
    volumes:
      - namenode:/hadoop/dfs/name
    profiles: ["hive"]

  # HADOOP DATANODE (hive)
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    profiles: ["hive"]

  # HIVE METASTORE (hive)
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    depends_on:
      - namenode
      - datanode
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hivemetastoredb:5432/metastore
      HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
      HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword: hive
      HIVE_METASTORE_PORT: 9083
    ports:
      - "9083:9083"
    profiles: ["hive"]

  # POSTGRES PARA HIVE (hive)
  hivemetastoredb:
    image: postgres:13
    container_name: hivemetastoredb
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    profiles: ["hive"]

  # IMPALA (impala)
  impala:
    image: bigdataeng/impala
    container_name: impala
    depends_on:
      - hive-metastore
      - namenode
      - datanode
    ports:
      - "21050:21050"   # Puerto JDBC
      - "25000:25000"   # Web UI opcional
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
      - IMPALA_STATE_STORE_HOST=impala
    profiles: ["impala"]

  # SPARK MASTER UI (spark)
  spark:
    image: bitnami/spark:3.3
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    profiles: ["spark"]

  # SPARK APP PYTHON (spark)
  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-app
    volumes:
      - ./src:/app
      - ./data:/app/data
    depends_on:
      - spark
    command: sleep infinity
    profiles: ["spark"]

volumes:
  namenode:
  datanode:
